import React, { useState } from 'react';
import { useShift } from '../context/ShiftContext';
import { 
  Calendar, 
  Clock, 
  CheckCircle2, 
  Circle, 
  Zap, 
  BookOpen, 
  Code, 
  Target, 
  Sparkles, 
  ChevronDown, 
  ChevronUp,
  Download,
  ExternalLink,
  Sliders,
  CalendarDays,
  Award
} from 'lucide-react';
import { RoadmapCustomizerModal } from './RoadmapCustomizerModal';

export const LearningPathView: React.FC = () => {
  const { 
    learningTasks, 
    toggleTaskCompletion, 
    profile, 
    setCurrentStep, 
    latestAdaptiveEvent,
    clearAdaptiveBanner,
    loadDemoScenario,
    scheduleBlocks,
    weeklyMilestones
  } = useShift();

  const [expandedTaskId, setExpandedTaskId] = useState<string | null>(learningTasks[0]?.id || null);
  const [activeTab, setActiveTab] = useState<'tasks' | 'schedule' | 'milestones'>('tasks');
  const [isCustomizerOpen, setIsCustomizerOpen] = useState(false);

  const totalBudgetHours = Math.round(profile.weeklyHours * (profile.durationDays / 7));
  const allocatedHours = Math.round(learningTasks.reduce((acc, t) => acc + t.estimatedHours, 0) * 10) / 10;
  const completedCount = learningTasks.filter(t => t.completed).length;
  const progressPercent = learningTasks.length > 0 ? Math.round((completedCount / learningTasks.length) * 100) : 0;

  if (learningTasks.length === 0) {
    return (
      <div className="max-w-[1280px] mx-auto py-16 px-6 text-center">
        <div className="bg-[#101416] border border-[rgba(250,243,225,0.14)] rounded-[26px] p-10 max-w-lg mx-auto shadow-2xl">
          <Target className="w-12 h-12 text-[#FF6D1F] mx-auto mb-4" />
          <h2 className="font-display text-2xl font-bold uppercase text-[#FAF3E1]">
            No Learning Sprint Generated
          </h2>
          <p className="text-xs text-[#96928A] mt-2 mb-6 leading-relaxed">
            Generate a personalized 7 or 14-day learning sprint budgeted to your weekly available hours.
          </p>

          <div className="flex flex-col gap-3">
            <button
              onClick={() => setCurrentStep('setup')}
              className="w-full py-3.5 rounded-[22px] bg-[#FF6D1F] hover:bg-[#ff7e36] text-[#222222] font-black text-xs uppercase tracking-wider font-display transition cursor-pointer shadow-lg shadow-[#FF6D1F]/20"
            >
              START CAREER SETUP →
            </button>
            <button
              onClick={() => {
                loadDemoScenario('prd_frontend_beginner');
                setCurrentStep('path');
              }}
              className="w-full py-3 rounded-[20px] bg-[#080B0D] hover:bg-[#1a2024] text-[#FAF3E1] border border-[rgba(250,243,225,0.18)] text-xs font-semibold flex items-center justify-center gap-2 cursor-pointer font-display transition"
            >
              <Zap className="w-4 h-4 text-[#FF6D1F]" />
              <span>Explore an example roadmap</span>
            </button>
          </div>
        </div>
      </div>
    );
  }

  const handleExportMarkdown = () => {
    const mdContent = `# SkillForge AI Engineering Roadmap: ${profile.targetRoleTitle} (${profile.durationDays}-Day Sprint)
Generated by SkillForge AI — Engineering Career Workspace
Weekly Availability: ${profile.weeklyHours} hrs/week | Total Budget: ${allocatedHours} hrs

## Summary
- Target Role: ${profile.targetRoleTitle}
- Candidate Experience: ${profile.experienceLevel}
- Tasks Completed: ${completedCount} of ${learningTasks.length}

---

## Sprint Action Plan
${learningTasks.map(t => `
### Day ${t.dayNumber}: ${t.title} [${t.priority} Priority]
- **Skill Competency:** ${t.skill}
- **Estimated Hours:** ${t.estimatedHours}h
- **Checklist Status:** ${t.completed ? '[x] Completed' : '[ ] Pending'}
${t.adaptedFromInterview ? `- **Adapted By Interview Performance:** ${t.adaptationReason}\n` : ''}
- **Why This Matters:** ${t.reasonItMatters}
- **Learning Action:** ${t.learningAction}
- **Practice Task:** ${t.practiceTask}
- **Expected Outcome:** ${t.expectedOutcome}
`).join('\n---\n')}
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SkillForge-${profile.targetRole}-${profile.durationDays}d-roadmap.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const getCuratedResource = (skill: string) => {
    const s = skill.toLowerCase();
    if (s.includes('react')) return { name: 'React.dev Official Documentation', url: 'https://react.dev' };
    if (s.includes('javascript')) return { name: 'MDN Web Docs (JavaScript Guide)', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' };
    if (s.includes('sql')) return { name: 'PostgreSQL Official Documentation', url: 'https://www.postgresql.org/docs/' };
    if (s.includes('python') || s.includes('pandas')) return { name: 'Pandas User Guide & Exercises', url: 'https://pandas.pydata.org/docs/' };
    if (s.includes('api') || s.includes('rest')) return { name: 'MDN HTTP & REST Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP' };
    if (s.includes('css') || s.includes('flexbox')) return { name: 'MDN CSS Layout & Flexbox Guide', url: 'https://developer.mozilla.org/en-US/docs/Learn/CSS' };
    return { name: 'MDN Web Technology Reference', url: 'https://developer.mozilla.org' };
  };

  return (
    <div className="max-w-[1280px] mx-auto py-10 px-6 sm:px-10">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-[rgba(250,243,225,0.12)]">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="font-mono text-xs font-bold uppercase tracking-widest text-[#FF6D1F]">
              Engineering Roadmap
            </span>
            <span className="text-[#96928A]">•</span>
            <span className="text-xs text-[#96928A]">Capacity-Budgeted Action Plan</span>
          </div>
          <h1 className="font-display text-4xl sm:text-5xl font-black uppercase text-[#FAF3E1] tracking-tight">
            {profile.durationDays}-Day Engineering Roadmap
          </h1>
          <p className="text-sm text-[#96928A] mt-2">
            Budgeted strictly to your <span className="text-[#FF6D1F] font-bold">{profile.weeklyHours} hrs/week</span> schedule. Focuses directly on closing verified engineering gaps.
          </p>
        </div>

        <div className="flex items-center gap-3 self-start sm:self-center">
          {/* P1: Download Sprint Plan */}
          <button
            onClick={() => setIsCustomizerOpen(true)}
            title="Configure study days, hours, and intensity"
            className="px-5 py-3.5 rounded-[22px] bg-[#101416] hover:bg-[#1a2024] text-[#FAF3E1] border border-[rgba(250,243,225,0.2)] font-bold text-xs uppercase tracking-wider transition flex items-center gap-2 cursor-pointer font-display"
          >
            <Sliders className="w-4 h-4 text-[#FF6D1F]" />
            <span>Customize Schedule</span>
          </button>

          <button
            onClick={handleExportMarkdown}
            title="Download formatted Markdown sprint document"
            className="px-5 py-3.5 rounded-[22px] bg-[#101416] hover:bg-[#1a2024] text-[#FAF3E1] border border-[rgba(250,243,225,0.2)] font-bold text-xs uppercase tracking-wider transition flex items-center gap-2 cursor-pointer font-display"
          >
            <Download className="w-4 h-4 text-[#FF6D1F]" />
            <span>Export Plan (.md)</span>
          </button>

          <button
            onClick={() => setCurrentStep('interview')}
            className="px-6 py-3.5 rounded-[22px] bg-[#FF6D1F] hover:bg-[#ff7e36] text-[#222222] font-black text-xs uppercase tracking-wider transition flex items-center gap-2 cursor-pointer font-display shadow-lg shadow-[#FF6D1F]/20"
          >
            <span>START INTERVIEW PRACTICE →</span>
          </button>
        </div>
      </div>

      {/* Adaptive Banner Notification: "This changed because…" */}
      {latestAdaptiveEvent && (
        <div className="bg-[#101416] border-2 border-[#FF6D1F] rounded-[26px] p-6 mb-8 shadow-2xl shadow-[#FF6D1F]/10 animate-badge-pop">
          <div className="flex items-start justify-between gap-3">
            <div className="flex items-start gap-4">
              <div className="w-11 h-11 rounded-2xl bg-[#FF6D1F]/20 border border-[#FF6D1F]/40 flex items-center justify-center text-[#FF6D1F] flex-shrink-0 mt-0.5">
                <Zap className="w-6 h-6 animate-pulse" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="font-display text-sm font-bold uppercase tracking-wider text-[#FF6D1F]">
                    Your Next Move Adapted
                  </span>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-[#FF6D1F]/20 text-[#FF6D1F] font-bold">
                    Feedback Loop Active
                  </span>
                </div>
                <h3 className="font-display text-xl font-bold uppercase text-[#FAF3E1] mt-1">
                  Reprioritized: {latestAdaptiveEvent.taskMovedTitle}
                </h3>
                <p className="text-xs text-[#FAF3E1] mt-1.5 leading-relaxed">
                  <strong className="text-[#FF6D1F]">This changed because…</strong> {latestAdaptiveEvent.reason}
                </p>
                <div className="flex items-center gap-4 mt-3 text-xs font-mono text-[#FAF3E1]">
                  <span>Shift: {latestAdaptiveEvent.fromPosition} → <strong className="text-[#FF6D1F] underline">{latestAdaptiveEvent.toPosition}</strong></span>
                  <span>Signal: {latestAdaptiveEvent.skillSignal}</span>
                </div>
              </div>
            </div>
            <button
              onClick={clearAdaptiveBanner}
              className="text-xs text-[#96928A] hover:text-[#FAF3E1] px-3 py-1 rounded-full bg-[#080B0D] border border-[rgba(250,243,225,0.1)] cursor-pointer"
            >
              Dismiss
            </button>
          </div>
        </div>
      )}

      {/* Time-Budget & Progress Bar */}
      <div className="bg-[#101416] border border-[rgba(250,243,225,0.14)] rounded-[26px] p-7 mb-8 shadow-xl">
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-6 mb-6">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-[#96928A]">Sprint Goal</span>
            <div className="font-display text-2xl font-black text-[#FAF3E1] mt-1 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-[#FF6D1F]" />
              <span>{profile.durationDays} Days</span>
            </div>
            <p className="text-[11px] text-[#96928A] mt-0.5">{profile.durationDays === 14 ? '2 Weeks' : '1 Week'} sprint</p>
          </div>

          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-[#96928A]">Weekly Availability</span>
            <div className="font-display text-2xl font-black text-[#FAF3E1] mt-1 flex items-center gap-2">
              <Clock className="w-4 h-4 text-[#FF6D1F]" />
              <span>{profile.weeklyHours} hrs/wk</span>
            </div>
            <p className="text-[11px] text-[#96928A] mt-0.5">Budgeted for student schedule</p>
          </div>

          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-[#96928A]">Total Time Budget</span>
            <div className="font-display text-2xl font-black text-[#B8D88A] mt-1">
              {allocatedHours} / {totalBudgetHours} hrs
            </div>
            <p className="text-[11px] text-[#96928A] mt-0.5">Allocated vs Capacity</p>
          </div>

          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-[#96928A]">Checklist Progress</span>
            <div className="font-display text-2xl font-black text-[#FAF3E1] mt-1">
              {completedCount} of {learningTasks.length} ({progressPercent}%)
            </div>
            <p className="text-[11px] text-[#96928A] mt-0.5">Mark tasks complete as you finish</p>
          </div>
        </div>

        {/* Progress Bar */}
        <div className="w-full bg-[rgba(250,243,225,0.14)] h-2 rounded-full overflow-hidden">
          <div 
            className="bg-[#FF6D1F] h-full rounded-full transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* View Mode Tabs */}
      <div className="flex flex-wrap items-center gap-2 mb-6 border-b border-[rgba(250,243,225,0.12)] pb-4">
        <button
          onClick={() => setActiveTab('tasks')}
          className={`px-4 py-2.5 rounded-xl text-xs font-bold font-display uppercase tracking-wider transition flex items-center gap-2 ${
            activeTab === 'tasks'
              ? 'bg-[#FF6D1F] text-[#222222] shadow-md shadow-[#FF6D1F]/20'
              : 'bg-[#101416] text-[#96928A] hover:text-[#FAF3E1] border border-[rgba(250,243,225,0.1)]'
          }`}
        >
          <Target className="w-3.5 h-3.5" />
          <span>Curriculum Tasks ({learningTasks.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('schedule')}
          className={`px-4 py-2.5 rounded-xl text-xs font-bold font-display uppercase tracking-wider transition flex items-center gap-2 ${
            activeTab === 'schedule'
              ? 'bg-[#FF6D1F] text-[#222222] shadow-md shadow-[#FF6D1F]/20'
              : 'bg-[#101416] text-[#96928A] hover:text-[#FAF3E1] border border-[rgba(250,243,225,0.1)]'
          }`}
        >
          <CalendarDays className="w-3.5 h-3.5" />
          <span>Hourly Study Timeline ({scheduleBlocks.length} Blocks)</span>
        </button>

        <button
          onClick={() => setActiveTab('milestones')}
          className={`px-4 py-2.5 rounded-xl text-xs font-bold font-display uppercase tracking-wider transition flex items-center gap-2 ${
            activeTab === 'milestones'
              ? 'bg-[#FF6D1F] text-[#222222] shadow-md shadow-[#FF6D1F]/20'
              : 'bg-[#101416] text-[#96928A] hover:text-[#FAF3E1] border border-[rgba(250,243,225,0.1)]'
          }`}
        >
          <Award className="w-3.5 h-3.5" />
          <span>Weekly Sprint Milestones ({weeklyMilestones.length})</span>
        </button>
      </div>

      {/* Task Cards */}
      {activeTab === 'tasks' && (
      <div className="space-y-4 mb-12">
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-display text-xl font-bold uppercase text-[#FAF3E1] flex items-center gap-2">
            <Target className="w-5 h-5 text-[#FF6D1F]" />
            Your Targeted Tasks ({learningTasks.length})
          </h2>
          <span className="text-xs text-[#96928A]">Click task card to inspect practice task & deliverable</span>
        </div>

        {learningTasks.map((task) => {
          const isExpanded = expandedTaskId === task.id;
          const resource = getCuratedResource(task.skill);
          return (
            <div
              key={task.id}
              className={`rounded-[22px] border transition-all duration-200 overflow-hidden ${
                task.completed
                  ? 'bg-[#080B0D]/80 border-[rgba(250,243,225,0.08)] opacity-65'
                  : task.adaptedFromInterview
                  ? 'bg-[#101416] border-2 border-[#FF6D1F] shadow-xl shadow-[#FF6D1F]/10'
                  : 'bg-[#101416] border-[rgba(250,243,225,0.14)] hover:border-[rgba(250,243,225,0.25)]'
              }`}
            >
              {/* Task Header Row */}
              <div 
                className="p-5 flex items-center justify-between gap-4 cursor-pointer"
                onClick={() => setExpandedTaskId(isExpanded ? null : task.id)}
              >
                <div className="flex items-center gap-4 flex-1">
                  {/* Completion Checkbox */}
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      toggleTaskCompletion(task.id);
                    }}
                    className="p-1 text-[#96928A] hover:text-[#B8D88A] transition cursor-pointer flex-shrink-0"
                    title={task.completed ? 'Mark incomplete' : 'Mark completed'}
                  >
                    {task.completed ? (
                      <CheckCircle2 className="w-6 h-6 text-[#B8D88A]" />
                    ) : (
                      <Circle className="w-6 h-6 text-[#96928A] hover:text-[#FF6D1F]" />
                    )}
                  </button>

                  <div className="flex-1">
                    <div className="flex flex-wrap items-center gap-2 mb-1.5">
                      {/* Day Pill */}
                      <span className="text-[10px] font-mono font-bold uppercase px-2.5 py-0.5 rounded-full bg-[#080B0D] text-[#FAF3E1] border border-[rgba(250,243,225,0.14)]">
                        Day {task.dayNumber}
                      </span>

                      {/* Priority */}
                      <span className={`text-[10px] font-mono uppercase px-2.5 py-0.5 rounded-full border ${
                        task.priority === 'High'
                          ? 'bg-[#FF6D1F]/20 text-[#FF6D1F] border-[#FF6D1F]/40 font-bold'
                          : task.priority === 'Medium'
                          ? 'bg-[#F7C65B]/20 text-[#F7C65B] border-[#F7C65B]/40'
                          : 'bg-[#080B0D] text-[#96928A] border-[rgba(250,243,225,0.14)]'
                      }`}>
                        {task.priority} Priority
                      </span>

                      {/* Estimated Hours */}
                      <span className="text-[10px] font-mono text-[#FAF3E1] flex items-center gap-1 bg-[#080B0D] border border-[rgba(250,243,225,0.14)] px-2.5 py-0.5 rounded-full">
                        <Clock className="w-3 h-3 text-[#FF6D1F]" />
                        {task.estimatedHours} hrs
                      </span>

                      {/* Adapted Badge if applicable */}
                      {task.adaptedFromInterview && (
                        <span className="text-[10px] font-mono font-black uppercase px-3 py-0.5 rounded-full bg-[#FF6D1F] text-[#222222] flex items-center gap-1 animate-pulse">
                          <Zap className="w-3 h-3" />
                          Adapted By Interview
                        </span>
                      )}
                    </div>

                    <h3 className={`font-display text-lg font-bold uppercase ${task.completed ? 'line-through text-[#96928A]' : 'text-[#FAF3E1]'}`}>
                      {task.title}
                    </h3>
                    <p className="text-xs text-[#96928A] line-clamp-1 mt-0.5">
                      Skill Competency: <span className="text-[#FF6D1F] font-mono font-semibold">{task.skill}</span>
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2 text-[#96928A]">
                  {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                </div>
              </div>

              {/* Expanded Details Body */}
              {isExpanded && (
                <div className="px-6 pb-6 pt-2 border-t border-[rgba(250,243,225,0.1)] bg-[#080B0D] space-y-4">
                  {task.adaptationReason && (
                    <div className="bg-[#FF6D1F]/15 border border-[#FF6D1F]/40 rounded-[18px] p-4 text-xs text-[#FAF3E1] flex items-start gap-3">
                      <Zap className="w-4 h-4 text-[#FF6D1F] flex-shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-[#FF6D1F]">This changed because…</strong> {task.adaptationReason}
                      </div>
                    </div>
                  )}

                  {/* 1. Reason It Matters */}
                  <div className="bg-[#101416] rounded-[18px] p-4 border border-[rgba(250,243,225,0.1)]">
                    <div className="text-xs font-bold uppercase tracking-wider text-[#FAF3E1] flex items-center gap-2 mb-1.5">
                      <Target className="w-4 h-4 text-[#FF6D1F]" />
                      <span>Why this matters for your interview</span>
                    </div>
                    <p className="text-xs text-[#96928A] leading-relaxed">
                      {task.reasonItMatters}
                    </p>
                  </div>

                  {/* 2. Recommended Learning Action */}
                  <div className="bg-[#101416] rounded-[18px] p-4 border border-[rgba(250,243,225,0.1)]">
                    <div className="text-xs font-bold uppercase tracking-wider text-[#FAF3E1] flex items-center gap-2 mb-1.5">
                      <BookOpen className="w-4 h-4 text-[#FF6D1F]" />
                      <span>Recommended Learning Action</span>
                    </div>
                    <p className="text-xs text-[#96928A] leading-relaxed">
                      {task.learningAction}
                    </p>
                  </div>

                  {/* 3. Hands-on Practice Task */}
                  <div className="bg-[#101416] rounded-[18px] p-4 border border-[rgba(250,243,225,0.1)]">
                    <div className="text-xs font-bold uppercase tracking-wider text-[#FAF3E1] flex items-center gap-2 mb-1.5">
                      <Code className="w-4 h-4 text-[#FF6D1F]" />
                      <span>Practice This Next</span>
                    </div>
                    <p className="text-xs text-[#96928A] leading-relaxed">
                      {task.practiceTask}
                    </p>
                  </div>

                  {/* 4. Expected Outcome */}
                  <div className="bg-[#101416] rounded-[18px] p-4 border border-[rgba(250,243,225,0.1)]">
                    <div className="text-xs font-bold uppercase tracking-wider text-[#FAF3E1] flex items-center gap-2 mb-1.5">
                      <Sparkles className="w-4 h-4 text-[#B8D88A]" />
                      <span>Expected Outcome & Deliverable</span>
                    </div>
                    <p className="text-xs text-[#FAF3E1] leading-relaxed font-mono">
                      {task.expectedOutcome}
                    </p>
                  </div>

                  {/* P1: Curated Reference Resource */}
                  <div className="bg-[#101416] rounded-[18px] p-3.5 border border-[rgba(250,243,225,0.1)] flex items-center justify-between text-xs">
                    <span className="text-[#96928A] flex items-center gap-1.5">
                      <BookOpen className="w-3.5 h-3.5 text-[#FF6D1F]" />
                      <span>Curated Reference:</span>
                      <strong className="text-[#FAF3E1]">{resource.name}</strong>
                    </span>
                    <a
                      href={resource.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-[#FF6D1F] hover:underline font-mono text-[11px]"
                    >
                      <span>Documentation</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>

                  {/* Toggle button */}
                  <div className="pt-2 flex justify-end">
                    <button
                      type="button"
                      onClick={() => toggleTaskCompletion(task.id)}
                      className={`px-5 py-2.5 rounded-full text-xs font-bold uppercase tracking-wider transition cursor-pointer flex items-center gap-2 font-display ${
                        task.completed
                          ? 'bg-[#101416] text-[#96928A] hover:text-[#FAF3E1] border border-[rgba(250,243,225,0.14)]'
                          : 'bg-[#B8D88A] hover:bg-[#c9e89d] text-[#222222]'
                      }`}
                    >
                      {task.completed ? (
                        <>
                          <CheckCircle2 className="w-4 h-4 text-[#B8D88A]" />
                          <span>Task Completed (Click to Unmark)</span>
                        </>
                      ) : (
                        <>
                          <CheckCircle2 className="w-4 h-4" />
                          <span>Mark Task As Complete</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
      )}

      {/* Tab 2: Hourly Study Schedule */}
      {activeTab === 'schedule' && (
        <div className="space-y-6 mb-12 animate-in fade-in duration-200">
          <div className="flex items-center justify-between">
            <h2 className="font-display text-xl font-bold uppercase text-[#FAF3E1] flex items-center gap-2">
              <CalendarDays className="w-5 h-5 text-[#FF6D1F]" />
              Deterministic Hourly Schedule
            </h2>
            <button
              onClick={() => setIsCustomizerOpen(true)}
              className="text-xs text-[#FF6D1F] hover:underline font-bold font-display uppercase tracking-wider"
            >
              Adjust schedule capacity & days →
            </button>
          </div>

          {scheduleBlocks.length === 0 ? (
            <div className="p-8 text-center bg-[#101416] rounded-2xl border border-[rgba(250,243,225,0.1)] text-xs text-[#96928A]">
              No schedule blocks generated yet. Click "Customize Schedule" to initialize your study calendar.
            </div>
          ) : (
            <div className="space-y-4">
              {Array.from(new Set(scheduleBlocks.map(b => b.date))).map(dateStr => {
                const dayBlocks = scheduleBlocks.filter(b => b.date === dateStr);
                const dayLabel = dayBlocks[0]?.dayLabel || 'Day';
                return (
                  <div key={dateStr} className="bg-[#101416] border border-[rgba(250,243,225,0.1)] rounded-[22px] p-5 space-y-3">
                    <div className="flex items-center justify-between border-b border-[rgba(250,243,225,0.06)] pb-2.5">
                      <div className="flex items-center gap-2">
                        <span className="font-display font-bold text-[#FAF3E1] text-sm uppercase">{dayLabel}</span>
                        <span className="text-xs font-mono text-[#96928A]">{dateStr}</span>
                      </div>
                      <span className="text-xs text-[#FF6D1F] font-bold font-mono">
                        {dayBlocks.filter(b => b.type !== 'break').length} sessions scheduled
                      </span>
                    </div>

                    <div className="space-y-2">
                      {dayBlocks.map(block => (
                        <div
                          key={block.id}
                          className={`p-3.5 rounded-[16px] border flex items-center justify-between text-xs transition ${
                            block.type === 'break'
                              ? 'bg-white/5 border-dashed border-white/10 text-[#96928A]'
                              : block.type === 'project'
                              ? 'bg-amber-500/10 border-amber-500/20 text-amber-200'
                              : block.type === 'practice'
                              ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-200'
                              : block.type === 'interview'
                              ? 'bg-purple-500/10 border-purple-500/20 text-purple-200'
                              : 'bg-[#080B0D] border-[rgba(250,243,225,0.08)] text-[#FAF3E1]'
                          }`}
                        >
                          <div className="flex items-center gap-3">
                            <span className="font-mono text-[11px] font-bold text-[#FF6D1F] w-24">
                              {block.startTime} – {block.endTime}
                            </span>
                            <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase font-mono ${
                              block.type === 'break'
                                ? 'bg-white/10 text-[#96928A]'
                                : 'bg-[#FF6D1F]/20 text-[#FF6D1F]'
                            }`}>
                              {block.type}
                            </span>
                            <span className="font-medium text-xs">{block.title}</span>
                          </div>

                          <span className="text-[11px] text-[#96928A] font-mono">
                            {block.durationMinutes}m
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* Tab 3: Weekly Sprint Milestones */}
      {activeTab === 'milestones' && (
        <div className="space-y-6 mb-12 animate-in fade-in duration-200">
          <div className="flex items-center justify-between">
            <h2 className="font-display text-xl font-bold uppercase text-[#FAF3E1] flex items-center gap-2">
              <Award className="w-5 h-5 text-[#FF6D1F]" />
              Weekly Sprint Milestones & Evidence Goals
            </h2>
            <span className="text-xs text-[#96928A]">Sprint milestones tailored to hiring benchmarks</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {weeklyMilestones.map(m => (
              <div key={m.weekNumber} className="bg-[#101416] border border-[rgba(250,243,225,0.12)] rounded-[22px] p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider font-mono bg-[#FF6D1F]/20 text-[#FF6D1F] border border-[#FF6D1F]/30">
                    Week {m.weekNumber} Milestone
                  </span>
                  <span className="text-xs font-mono font-bold text-[#FAF3E1]/70">
                    {m.totalPlannedHours} Hours Total
                  </span>
                </div>

                <h3 className="font-display text-lg font-bold text-[#FAF3E1]">
                  {m.milestoneTitle}
                </h3>

                <div className="space-y-2 text-xs">
                  <div className="bg-[#080B0D] p-3.5 rounded-[16px] border border-white/5">
                    <span className="text-[#FF6D1F] font-bold block mb-1">Project Deliverable:</span>
                    <p className="text-[#FAF3E1]/80 leading-relaxed font-mono">{m.projectDeliverable}</p>
                  </div>

                  <div className="bg-[#080B0D] p-3.5 rounded-[16px] border border-white/5">
                    <span className="text-emerald-400 font-bold block mb-1">Assessment / Review Checkpoint:</span>
                    <p className="text-[#FAF3E1]/80 leading-relaxed">{m.assessmentOrReview}</p>
                  </div>

                  <div className="bg-[#080B0D] p-3.5 rounded-[16px] border border-white/5">
                    <span className="text-purple-400 font-bold block mb-1">Expected Proof Evidence:</span>
                    <p className="text-[#FAF3E1]/80 leading-relaxed">{m.expectedEvidence}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Navigation Footer */}
      <div className="flex justify-between items-center pt-4 border-t border-[rgba(250,243,225,0.12)]">
        <button
          onClick={() => setCurrentStep('gap')}
          className="text-xs text-[#96928A] hover:text-[#FAF3E1] font-medium cursor-pointer"
        >
          ← Back to Role Gap Benchmark
        </button>

        <button
          onClick={() => setCurrentStep('interview')}
          className="px-8 py-4 rounded-[26px] bg-[#FF6D1F] hover:bg-[#ff7e36] text-[#222222] font-black text-xs uppercase tracking-wider transition flex items-center gap-2 cursor-pointer font-display shadow-lg shadow-[#FF6D1F]/20"
        >
          <span>STEP 05: START TARGETED INTERVIEW PRACTICE →</span>
        </button>
      </div>

      {/* Customizer Modal */}
      <RoadmapCustomizerModal
        isOpen={isCustomizerOpen}
        onClose={() => setIsCustomizerOpen(false)}
      />
    </div>
  );
};
